# Generated by Django 3.0.8 on 2020-07-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='series',
            field=models.CharField(default='A SHOW', max_length=100),
            preserve_default=False,
        ),
    ]
